dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
dotenv: .env
networks:
  default: development
  mainnet:
    verify: True
  rinkeby:
    weth: '0xc778417E063141139Fce010982780140Aa0cD5Ab'
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
