name: Backend CI
on:
  pull_request:
    branches:
    - main
    paths:
    - backend/**
    types:
    - opened
    - reopened
    - synchronize
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1
    - name: Build
      run: go build -v ./...
      working-directory: backend
    - name: Test
      run: go test -v ./...
      working-directory: backend
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: backend
