name: Frontend CD
on:
  push:
    branches:
    - main
    paths:
    - frontend/**
  workflow_dispatch:
jobs:
  nextjs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        appdir: frontend
        branch: main
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: dappz-auction-frontend
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        procfile: "web: npm start"
        region: eu
