name: Frontend CD
on:
  push:
    branches:
    - main
    paths:
    - frontend/**
jobs:
  nextjs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: 17.7.1
    - name: Install Dependencies
      run: npm ci
      working-directory: frontend
    - name: Build
      run: npm run export
      working-directory: frontend
    - name: Lint
      run: npm run lint
      working-directory: frontend
    - name: Deploy
      uses: nwtgck/actions-netlify@v1.2
      with:
        production-deploy: true
        publish-dir: frontend/out
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
